force-app/main/default/objects/Product2/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>97</fullName>
                <label>Advertising</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>Bank Charges</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>Commissions &amp; fees</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>Disposal Fees</label>
            </value>
            <value>
                <fullName>100</fullName>
                <label>Dues &amp; Subscriptions</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>Insurance</label>
            </value>
            <value>
                <fullName>118</fullName>
                <label>Insurance - Liability</label>
            </value>
            <value>
                <fullName>102</fullName>
                <label>Legal &amp; Professional Fees</label>
            </value>
            <value>
                <fullName>103</fullName>
                <label>Meals and Entertainment</label>
            </value>
            <value>
                <fullName>105</fullName>
                <label>Office Expenses</label>
            </value>
            <value>
                <fullName>106</fullName>
                <label>Promotional</label>
            </value>
            <value>
                <fullName>124</fullName>
                <default>true</default>
                <label>Purchases</label>
            </value>
            <value>
                <fullName>107</fullName>
                <label>Rent or Lease</label>
            </value>
            <value>
                <fullName>108</fullName>
                <label>Repair &amp; Maintenance</label>
            </value>
            <value>
                <fullName>109</fullName>
                <label>Stationery &amp; Printing</label>
            </value>
            <value>
                <fullName>110</fullName>
                <label>Supplies</label>
            </value>
            <value>
                <fullName>111</fullName>
                <label>Taxes &amp; Licenses</label>
            </value>
            <value>
                <fullName>119</fullName>
                <label>Tools</label>
            </value>
            <value>
                <fullName>112</fullName>
                <label>Travel</label>
            </value>
            <value>
                <fullName>113</fullName>
                <label>Travel Meals</label>
            </value>
            <value>
                <fullName>134</fullName>
                <label>Uncategorized Expense</label>
            </value>
            <value>
                <fullName>114</fullName>
                <label>Utilities</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Income_Account__c.field-meta.xml
<CustomField>
    <fullName>Income_Account__c</fullName>
    <label>Income Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>184</fullName>
                <default>true</default>
                <label>Sales</label>
            </value>
            <value>
                <fullName>209</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>211</fullName>
                <label>Billable Expense Income</label>
            </value>
            <value>
                <fullName>181</fullName>
                <label>Discounts</label>
            </value>
            <value>
                <fullName>182</fullName>
                <label>Gross Receipts</label>
            </value>
            <value>
                <fullName>183</fullName>
                <label>Refunds-Allowances</label>
            </value>
            <value>
                <fullName>216</fullName>
                <label>Sales of Product Income</label>
            </value>
            <value>
                <fullName>212</fullName>
                <label>Uncategorized Income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Quick Books Online ID. If this field is filled out, we&apos;ve stored in QBO.</inlineHelpText>
    <label>QBO_Id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/QBO_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QBO_SyncToken__c</fullName>
    <label>QBO SyncToken</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBProductSync_Controller.cls
public with sharing class QBProductSync_Controller {

 
    @InvocableMethod(label='Sync Item' description='Creates and syncs product with QB item' category= 'Product2')
    public static void callFromFlow(List<Id> p2Id){
		Product2 p = [SELECT Id,
                      Name, 
                      QBO_Id__c, 
                      QBO_SyncToken__c,
                      Income_Account__c,
                      Expense_Account__c                 
              FROM Product2 
              WHERE Id =: p2Id[0]]; 
        
        QBCallout callout = new QBCallout();
        QBItemQueryJSON queryJson = callout.getItem(p);
        system.debug(queryJson);
        //Check if a item was found
        if(queryJson != null&&queryJson.QueryResponse.Item!=null){
            if(queryJson.QueryResponse.Item.size() == 1){
                p.QBO_Id__c = queryJson.QueryResponse.Item[0].Id;
                p.QBO_SyncToken__c = queryJson.QueryResponse.Item[0].SyncToken;
                //p.Income_Account__c = queryJson.QueryResponse.Item[0].IncomeAccountRef.value;
                //p.Expense_Account__c = queryJson.QueryResponse.Item[0].IncomeAccountRef.value;
            }else{
                //Multiple Customer Error Handling
               throw new ListException(); 
            }
        }else{
            QBItemResponseJSON res = callout.createItemCall(p);
            p.QBO_Id__c = res.Item.Id;
            p.QBO_SyncToken__c = res.Item.SyncToken;
            //p.Income_Account__c = queryJson.QueryResponse.Item[0].IncomeAccountRef.value;
        }
        //DML After Callouts
        update p;
        
    }
}