force-app/main/default/objects/Account/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <externalId>true</externalId>
    <label>QBO Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QBO_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QBO_SyncToken__c</fullName>
    <label>QBO SyncToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <label>QBO Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/QBO_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QBO_SyncToken__c</fullName>
    <label>QBO SyncToken</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Order</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <displayFormat>POI-{0000000000}</displayFormat>
        <label>Purchase Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Unit_Cost__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QBPOSync_Controller.cls
public with sharing class QBPOSync_Controller {
    
    public Id poId{get;set;}
    public Purchase_Order__c po {get;set;}

    public QBPOSync_Controller(ApexPages.StandardController stdController) {
        poId = ApexPages.currentPage().getParameters().get('id');
        po = [SELECT Id,
                     (Select Id, 
                     Product__c,
                     Product__r.Name,
                     Product__r.QBO_Id__c,
                     Quantity__c,
                     Unit_Cost__c,
                     Amount__c
                     From Purchase_Order_Items__r),
                      Name, 
                      QBO_Id__c, 
                      QBO_SyncToken__c,
                      Vendor_Account__r.contact__r.email,
                      Vendor_Account__r.Name,
                      Vendor_Account__r.Contact__r.Name,
                      Vendor_Account__r.ShippingStreet,
                      Vendor_Account__r.ShippingCity,
                      Vendor_Account__r.ShippingState,
                      Vendor_Account__r.ShippingPostalCode,
                      Vendor_Account__r.QBO_Id__c,
                      Vendor_Account__r.QBO_SyncToken__c
              FROM Purchase_Order__c 
              WHERE Id =: poId];
    }

    public Pagereference syncQB(){
        QBCallout callout = new QBCallout();
        QBPOQueryJSON queryJson = callout.getPurchaseOrder(po);
        system.debug(queryJson);
        //Check if a Purchase Order was found
        if(queryJson != null){
            if(queryJson.QueryResponse.PurchaseOrder.size() == 1){
                po.QBO_Id__c = queryJson.QueryResponse.PurchaseOrder[0].Id;
                po.QBO_SyncToken__c = queryJson.QueryResponse.PurchaseOrder[0].SyncToken;
            }else{
                //Multiple Customer Error Handling
               throw new ListException(); 
            }
        }
        QBPOResponseJSON res = callout.createPurchaseOrderCall(po,po.Purchase_Order_Items__r);
        
        po.QBO_Id__c = res.PurchaseOrder.Id;
        po.QBO_SyncToken__c = res.PurchaseOrder.SyncToken;
        
        //DML After Callouts
        update po;
        return new PageReference('/'+poId);
    }
}