force-app/main/default/objects/Account/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <externalId>true</externalId>
    <label>QBO Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QBO_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QBO_SyncToken__c</fullName>
    <label>QBO SyncToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <externalId>true</externalId>
    <label>QBO Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QBO_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QBO_SyncToken__c</fullName>
    <label>QBO SyncToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>Total__c - Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due On Receipt</fullName>
            </value>
            <value>
                <fullName>Net 10</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/QBO_Id__c.field-meta.xml
<CustomField>
    <fullName>QBO_Id__c</fullName>
    <label>QBO Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QBInvoice_Controller.cls
/**
 * This class is the controller for the Global Action 'Sync with QB'. This will glue the code from the QBCallout class to
 * make the QB integration function properly.
 */

public with sharing class QBInvoice_Controller {

    public Id invId{get;set;}
    public Invoice__c inv {get;set;}

    public QBInvoice_Controller(ApexPages.StandardController controller) {
        invId = controller.getRecord().Id;
        inv = [SELECT Id,
                     Due_Date__c,
                      Subtotal__c,
                       Name, 
                       QBO_Id__c, 
                       QBO_SyncToken__c,
                       Terms__c,
                       Description__c,
                       Work_Order__c,
                       Work_Order__r.Account.contact__r.email,
                       Work_Order__r.Account.QBO_Id__c,
                       Work_Order__r.Account.BillingCity,  
                       Work_Order__r.Account.BillingStreet,  
                       Work_Order__r.Account.BillingState,  
                       Work_Order__r.Account.BillingPostalCode,  
                       Work_Order__r.Account.BillingLatitude,  
                       Work_Order__r.Account.BillingLongitude,  
                       Work_Order__r.Account.BillingCountry,
                       Work_Order__r.Account.name,
                       Work_Order__r.Account.contact__r.Name,
                       Work_Order__r.Account.contact__r.Phone,
                       Work_Order__r.Account.ShippingCity, 
                       Work_Order__r.Account.ShippingStreet, 
                       Work_Order__r.Account.ShippingState, 
                       Work_Order__r.Account.ShippingPostalCode, 
                       Work_Order__r.Account.ShippingLatitude, 
                       Work_Order__r.Account.ShippingLongitude, 
                       Work_Order__r.Account.ShippingCountry 
                    FROM Invoice__c 
                    WHERE Id =: invId];
    }

    public Pagereference syncQB(){
        QBCallout callout = new QBCallout();

        QBInvoiceQueryJSON queryJson = callout.getInvoice(inv);

        //Check if an invoice was found
        if(queryJson != null){
            if(queryJson.QueryResponse.Invoice.size() == 1){
                inv.QBO_Id__c = queryJson.QueryResponse.Invoice[0].Id;
                inv.QBO_SyncToken__c = queryJson.QueryResponse.Invoice[0].SyncToken;
            }else{
                //Multiple Customer Error Handling
               throw new ListException(); 
            }
        }

        QBWorkOrder_Controller woController = new QBWorkOrder_Controller();
        woController.wrapWOliAndProduct(inv);

        QBInvoiceResponseJSON res = callout.createInvoiceFromWorkOrderCall(inv, woController.woliMap.values());
        
        inv.Due_Date__c = Date.valueOf(res.Invoice.DueDate);
        inv.QBO_Id__c = res.Invoice.Id;
        inv.QBO_SyncToken__c = res.Invoice.SyncToken;
        inv.tax__c = res.Invoice.TxnTaxDetail.TotalTax;
        inv.total__c = res.Invoice.TotalAmt;
        inv.Subtotal__c = res.Invoice.Balance;
        //DML After Callouts

        update inv;
        return new PageReference('/'+ invId);
    }
    
}